name = "toonstream-api"
main = "src/worker.js"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
account_id = "1a103a076478a565238354f2f779e25c"


[observability]
enabled = true
